:toc: right

++++
    <!-- styles -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="wiki-css/theme.css" rel="stylesheet" />
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">
    <link rel="icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">

    <div class="masthead">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav" role="navigation">
                        <!-- Logo and slogan -->
                        <li><a href="index.html"><i class="icon-home"></i><span class="hidden-phone">&nbsp;Home</span></a></li>
                        <li><a href="project.html"><i class="icon-star"></i><span class="hidden-phone">&nbsp;Project</span></a></li>
                        <li class="active"><a href="documentation.html"><i class="icon-book"></i><span class="hidden-phone">&nbsp;Documentation</span></a></li>
                        <li><a href="contact.html"><i class="icon-envelope"></i><span class="hidden-phone">&nbsp;Contact</span></a></li>
                        <li><a href="https://github.com/wuic/wuic" target="_blank" title="Wuic Github"><i class="icon-github"></i><span class="hidden-phone">&nbsp;Github</span></a></li>
                        <li><a href="https://twitter.com/wuic_project" target="_blank"><i class="icon-twitter"></i><span class="hidden-phone">&nbsp;Twitter</span></a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    </div>
++++

== Extend WUIC

=== Why extend?

You may extend WUIC for several purposes:

* Create a new way to access nuts, this is done with a http://wuic.github.io/apidocs/com/github/wuic/nut/dao/NutDao.html[DAO]
* Create a new nut processor, this is done with an http://wuic.github.io/apidocs/com/github/wuic/engine/Engine.htm[engine]
* Create a support for a templating project to write HTML statements that load processed nuts

=== Resolve and process nuts differently

Both DAO (TODO: migrate https://github.com/wuic/wuic/wiki/Data-Access-Object) and Engines (TODO: migrate https://github.com/wuic/wuic/wiki/Engine-configuration) can be configured in a XML configuration file. You can also do it with [Java Config](https://github.com/wuic/wuic/wiki/Configuring-with-Java-Config#use-the-contextbuilder).

To do it, WUIC provides its own annotation processor architecture which detects all classes:

* implementing `NutDao`, annotated http://wuic.github.io/apidocs/com/github/wuic/nut/dao/NutDaoService.html[@NutDaoService] and declared in package `com.github.wuic.dao`
* extending `Engine`, annotated http://wuic.github.io/apidocs/com/github/wuic/engine/EngineService.html[@EngineService] and declared in package `com.github.wuic.engine`

So you can create a new DAO like this:

[source,java]
----
package com.github.wuic.dao;

@NutDaoService
public class MyNutDao extends AbstractNutDao {
   ...
}
----

and an engine like this:

[source,java]
----
package com.github.wuic.engine;

@EngineService(injectDefaultToWorkflow = true)
public class MyEngine extends NodeEngine {
   ...
}
----

In this last example you can see the `injectDefaultToWorkflow` annotation attribute that indicates that this engine will be
in any workflow by default or not

Note that the code above uses base class that help you to implement `NutDao` interface and extend `Engine` class.
You will find a lot of helpers in the javadoc:

* http://wuic.github.io/apidocs/com/github/wuic/engine/core/package-summary.html[Abstract classes] for engine with different purpose (caching, aggregating, compressing, etc)
* http://wuic.github.io/apidocs/com/github/wuic/nut/AbstractNutDao.html[AbstractNutDao] for DAO creation

Each engine and DAO needs to be configured differently so your class may expose a constructor expecting several parameters.
You need in that case to rely on http://wuic.github.io/apidocs/com/github/wuic/config/package-summary.html[com.github.wuic.config] package which contains:

* `@ConfigConstructor` annotation for you constructor
* Annotations for each parameter regarding their type: `String`, `Integer`, `Boolean` or more global `Object`

For instance, an engine compressing nuts will looks like this:

[source,java]
----
include::{wuic-repository}wuic/core/src/test/java/com/github/wuic/test/ApiTutorial.java[tags=EngineService]
----

http://wuic.github.io/apidocs/com/github/wuic/ApplicationConfig.html[ApplicationConfig] already contains a lot of configuration keys that you can reuse.
This is required to let WUIC build the object for you regarding the properties provided in `XML` or `Java Config`.
With the previous sample, you can now do something like that in XML:

[source,xml]
----
<wuic>
   <engine-builders>
       <engine-builder type="MyCompressEngineBuilder">
           <property key="c.g.wuic.engine.compress">false</property>
       </engine-builder>
   </engine-builders>
</wuic>
----

WUIC generates a builder identified by `[EngineName]Builder` and by default injects a default instance identified by `wuicDefault[BuilderName]` into the workflow.
The previous configuration simply changes the default value (`true` to `false`).

You will find several extensions already provided https://github.com/wuic/wuic-extensions[here].

=== Add support for templating project

WUIC already provides support for `JSP` and `Thymeleaf` users (link:tutorials.html[see tutorials]).

Both support address the same issues:

* How to generate 1 HTTP request to load an aggregate result vs N HTTP requests when aggregation is disabled
* How to manage configurations directly injected into the template and cache it to improve performances

==== Generate script import

To generate script import, you need to loop over the list returned by the workflow process:

[source,java]
----
include::{wuic-repository}wuic/core/src/test/java/com/github/wuic/test/ApiTutorial.java[tags=WriteScriptImport]
----

Regarding your configuration, the process for a particular workflow will return a different result.
For instance, the list will contain only one element per script type if aggregation is enabled, many otherwise.

==== Allow configuration from templating

You can also use the facade to specify additional configurations through templating support.
You can rely on http://wuic.github.io/apidocs/com/github/wuic/ContextBuilderConfigurator.html[ContextBuilderConfigurator] to configure the facade.
For instance, imagine a `Reader` points to the XML declared inside your template, then you can inject it like this:

[source,java]
----
include::{wuic-repository}wuic/core/src/test/java/com/github/wuic/test/ApiTutorial.java[tags=Configure]
----

Note: `wuicFacade.allowsMultipleConfigInTagSupport()` returns the http://wuic.github.io/apidocs/com/github/wuic/ApplicationConfig.html#WUIC_SERVLET_MULTIPLE_CONG_IN_TAG_SUPPORT[setting] that allows to configure only once (production mode) or multiple times (development mode).

You will find full samples in https://github.com/wuic/wuic/tree/wuic-0.5.x-snapshot/wuic/tag[JSP] and https://github.com/wuic/wuic-extensions/tree/wuic-0.5.x-snapshot/thymeleaf[Thymeleaf] support.

++++
<!-- javascript
=================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-40383819-1', 'github.io');
    ga('send', 'pageview');
</script>
++++