:toc: right

++++
    <!-- styles -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="wiki-css/theme.css" rel="stylesheet" />
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">
    <link rel="icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">

    <div class="masthead">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav" role="navigation">
                        <!-- Logo and slogan -->
                        <li><a href="index.html"><i class="icon-home"></i><span class="hidden-phone">&nbsp;Home</span></a></li>
                        <li><a href="project.html"><i class="icon-star"></i><span class="hidden-phone">&nbsp;Project</span></a></li>
                        <li class="active"><a href="wuic-documentation.html"><i class="icon-book"></i><span class="hidden-phone">&nbsp;Documentation</span></a></li>
                        <li><a href="contact.html"><i class="icon-envelope"></i><span class="hidden-phone">&nbsp;Contact</span></a></li>
                        <li><a href="https://github.com/wuic/wuic" target="_blank" title="Wuic Github"><i class="icon-github"></i><span class="hidden-phone">&nbsp;Github</span></a></li>
                        <li><a href="https://twitter.com/wuic_project" target="_blank"><i class="icon-twitter"></i><span class="hidden-phone">&nbsp;Twitter</span></a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    </div>
++++

== Custom workflow

=== Purpose

By default, WUIC uses transparently a default instance of each detected engine.
Automatically, your nuts will be aggregated, inspected, compressed, etc, but this could be changed!

This tutorial shows how you can take the complete control over the engines WUIC uses when processing nuts.

=== Configuration

Imagine you want that your nuts are only compressed by `YUCompressor` and cached by `EhCache`.
One possibility is to configure other engines to disable it but you can even remove them from the engines chain!

Let's see the following configuration that defines nuts heaps imported with `Thymeleaf`.

[source,xml]
----
    <heap id="css" dao-builder-id="myDao">
        <nut-path>css/foo.css</nut-path>
    </heap>
    <heap id="js" dao-builder-id="myDao">
        <nut-path>js/foo.js</nut-path>
    </heap>
----

[source,xml]
----
<wuic:html-import workflowId="css" />
<wuic:html-import workflowId="js" />
----

At this stage, you could think that the possible imports are based on the existing heaps.
That's wrong! Actually, when you import a set of nuts, this is done through a workflow.
A workflow processes some heaps with particular engines.
Why we did not declare them before? Because WUIC creates a workflow for each heap by default.
Its ID is the heap ID so that's why you could import some nuts with the ID of your heap.

Actually, to create a workflow, you need to refer to a workflow template which describes all the engines to be used.
When a workflow is created automatically for a heap, WUIC use a default template with some default engines:

* A cache based on a memory map for all type of nuts
* A text aggregator for scripts
* An image aggregator and an image compressor for images
* etc

So if we want to specify specific engines in a workflow, we have to declare it:

[source,xml]
----
    <workflow-templates>
        <workflow-template id="tpl">
            <without>
                <engine-builder-id>wuicDefaultMemoryMapCacheEngineBuilder</engine-builder-id>
            </without>
            <engine-chain>
                <engine-builder-id>wuicDefaultEhCacheEngineBuilder</engine-builder-id>
                <engine-builder-id>wuicDefaultYuiCompressorJavascriptEngineBuilder</engine-builder-id>
                <engine-builder-id>wuicDefaultYuiCompressorCssEngineBuilder</engine-builder-id>
            </engine-chain>
        </workflow-template>
    </workflow-templates>

    <workflows>
        <workflow id-prefix="my-" workflow-template-id="tpl" heap-id-pattern=".*" />
    </workflows>
----

* Note that we have excluded the cache based on a memory map because we only want to use `EhCache` to cache nuts
* As it is done for DAOs, WUIC creates default engine builders so you can refer there ID.
* `id-prefix` is a string that prefix the workflow ID which will be followed by the heap ID.
* `heap-id-pattern` is a regular expression which defines the heaps to be processed by the engines specified in this workflow.
* By default, compression is enabled on YUI Compressor engines
* By default, cache is enabled in EhCache engine which looks for a cache named `wuicCache` in a `ehcache.xml` file at the root of the classpath. If the cache is not found, it creates a default one.

With this configuration, WUIC will pick up appropriate engines for the nuts to be processed.
For instance, `YUICompressor` CSS minifier won't be applied on a heap composed of Javascript nuts.
Moreover, they will be chained according to their type.
For instance, caching engine is already executed first in the chain of responsibility.

* Note that if a heap is referenced in a custom workflow, then its default one won't be created.
* Also note that default engine will be injected if they are not in conflict with a specified one. In this case, cache based on memory map won't be injected because we already specify `EhCache` support.

Finally, you will import your heap through your custom workflow like that:

[source,xml]
----
<wuic:html-import workflowId="my-css" />
<wuic:html-import workflowId="my-js" />
----

== Extend WUIC

=== Why extend?

You may extend WUIC for several purposes:

* Create a new way to access nuts, this is done with a http://wuic.github.io/apidocs/com/github/wuic/nut/dao/NutDao.html[DAO]
* Create a new nut processor, this is done with an http://wuic.github.io/apidocs/com/github/wuic/engine/Engine.htm[engine]
* Create a support for a templating project to write HTML statements that load processed nuts

=== Resolve and process nuts differently

Both link:api.html#_configuring_the_nutdao[DAO] and link:api.html#_configuring_the_engines[Engines] can be configured in a XML configuration file.
You can also do it with link:api.html#_java_config[Java Config].

To do it, WUIC provides its own annotation processor architecture which detects all classes:

* implementing `NutDao`, annotated http://wuic.github.io/apidocs/com/github/wuic/nut/dao/NutDaoService.html[@NutDaoService] and declared in package `com.github.wuic.dao`
* extending `Engine`, annotated http://wuic.github.io/apidocs/com/github/wuic/engine/EngineService.html[@EngineService] and declared in package `com.github.wuic.engine`

So you can create a new DAO like this:

[source,java]
----
package com.github.wuic.dao;

@NutDaoService
public class MyNutDao extends AbstractNutDao {
   ...
}
----

and an engine like this:

[source,java]
----
package com.github.wuic.engine;

@EngineService(injectDefaultToWorkflow = true)
public class MyEngine extends NodeEngine {
   ...
}
----

In this last example you can see the `injectDefaultToWorkflow` annotation attribute that indicates that this engine will be
in any workflow by default or not

Note that the code above uses base class that help you to implement `NutDao` interface and extend `Engine` class.
You will find a lot of helpers in the javadoc:

* http://wuic.github.io/apidocs/com/github/wuic/engine/core/package-summary.html[Abstract classes] for engine with different purpose (caching, aggregating, compressing, etc)
* http://wuic.github.io/apidocs/com/github/wuic/nut/AbstractNutDao.html[AbstractNutDao] for DAO creation

Each engine and DAO needs to be configured differently so your class may expose a init-method expecting several parameters.
You need in that case to rely on http://wuic.github.io/apidocs/com/github/wuic/config/package-summary.html[com.github.wuic.config] package which contains:

* `@Config` annotation for your initialization method
* Annotations for each parameter regarding their type: `String`, `Integer`, `Boolean` or more global `Object`

For instance, an engine compressing nuts will looks like this:

[source,java]
----
include::{wuic-repository}wuic/core/src/test/java/com/github/wuic/test/ApiTutorial.java[tags=EngineService]
----

One your class is written, you just need to add to your classpath (typically `src/main/resources` in maven project)
a file containing your class name that will be called:

* `com.github.wuic.engine.Engine` if the component you wrote is an engine
* `com.github.wuic.nut.dao.NutDao` if the component your wrote is DAO
* `com.github.wuic.nut.filter.NutFilter` if the component your wrote is a filter

See link:https://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html[ServiceLoader] documentation for more information.

INFORMATION: Any method correctly annotated will be executed after the instantiation.

http://wuic.github.io/apidocs/com/github/wuic/ApplicationConfig.html[ApplicationConfig] already contains a lot of configuration keys that you can reuse.
This is required to let WUIC build the object for you regarding the properties provided in `XML` or `Java Config`.
With the previous sample, you can now do something like that in XML:

[source,xml]
----
<wuic>
   <engine-builders>
       <engine-builder type="MyCompressEngineBuilder">
           <property key="c.g.wuic.engine.compress">false</property>
       </engine-builder>
   </engine-builders>
</wuic>
----

WUIC generates a builder identified by `[EngineName]Builder` and by default injects a default instance identified by `wuicDefault[BuilderName]` into the workflow.
The previous configuration simply changes the default value (`true` to `false`).

You will find several extensions already provided https://github.com/wuic/wuic-extensions[here].

==== Extend the text inspection process

During process, `CSS` and `JS` files are inspected to resolve resources to be optimized inside their content.

For each type of script, a particular type of http://wuic.github.io/apidocs/com/github/wuic/engine/core/TextInspectorEngine.html[TextInspectorEngine] is used.
A `TextInspectorEngine` relies on a collection of http://wuic.github.io/apidocs/com/github/wuic/engine/LineInspector.html[LineInspector] to inspect a content.
A `LineInspector` has a specific and simple task: detecting a resource.

Out of the box, WUIC provides several `LineInspector` but some times you would like to add your own inspector to provide a level of resource detection support not provided by default.
For instance, URLs can be handled in many way in javascript.
User should be able to write a simple `LineInspector` with a regex to match the URL regarding the way he writes his application.

To achieve this, simple create an implementation of http://wuic.github.io/apidocs/com/github/wuic/engine/LineInspectorFactory.html[LineInspectorFactory].
This class is loaded thanks to the `ServiceLoader` available since Java 6 and therefore must provide a default constructor.
As also required by the `ServiceLoader`, you have to declare the complete class name of your implementation in a file named
`META-INF/services/com.github.wuic.engine.LineInspectorFactory` that needs to be available in your classpath.

=== Add support for templating project

WUIC already provides support for `JSP` and `Thymeleaf` users (link:tutorials.html[see tutorials]).

Both support address the same issues:

* How to generate 1 HTTP request to load an aggregate result vs N HTTP requests when aggregation is disabled
* How to manage configurations directly injected into the template and cache it to improve performances

==== Generate script import

To generate script import, you need to loop over the list returned by the workflow process:

[source,java]
----
include::{wuic-repository}wuic/core/src/test/java/com/github/wuic/test/ApiTutorial.java[tags=WriteScriptImport]
----

Regarding your configuration, the process for a particular workflow will return a different result.
For instance, the list will contain only one element per script type if aggregation is enabled, many otherwise.

==== Allow configuration from templating

You can also use the facade to specify additional configurations through templating support.
You can rely on http://wuic.github.io/apidocs/com/github/wuic/ContextBuilderConfigurator.html[ContextBuilderConfigurator] to configure the facade.
For instance, imagine a `Reader` points to the XML declared inside your template, then you can inject it like this:

[source,java]
----
include::{wuic-repository}wuic/core/src/test/java/com/github/wuic/test/ApiTutorial.java[tags=Configure]
----

Note: `wuicFacade.allowsMultipleConfigInTagSupport()` returns the http://wuic.github.io/apidocs/com/github/wuic/ApplicationConfig.html#WUIC_SERVLET_MULTIPLE_CONG_IN_TAG_SUPPORT[setting] that allows to configure only once (production mode) or multiple times (development mode).

You will find full samples in https://github.com/wuic/wuic/tree/wuic-0.5.x-snapshot/wuic/tag[JSP] and https://github.com/wuic/wuic-extensions/tree/wuic-0.5.x-snapshot/thymeleaf[Thymeleaf] support.

++++
<!-- javascript
=================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-40383819-1', 'github.io');
    ga('send', 'pageview');
</script>
++++