:toc: right

++++
    <!-- styles -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="wiki-css/theme.css" rel="stylesheet" />
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">
    <link rel="icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">

    <div class="masthead">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav" role="navigation">
                        <!-- Logo and slogan -->
                        <li><a href="index.html"><i class="icon-home"></i><span class="hidden-phone">&nbsp;Home</span></a></li>
                        <li><a href="project.html"><i class="icon-star"></i><span class="hidden-phone">&nbsp;Project</span></a></li>
                        <li class="active"><a href="documentation.html"><i class="icon-book"></i><span class="hidden-phone">&nbsp;Documentation</span></a></li>
                        <li><a href="contact.html"><i class="icon-envelope"></i><span class="hidden-phone">&nbsp;Contact</span></a></li>
                        <li><a href="https://github.com/wuic/wuic" target="_blank" title="Wuic Github"><i class="icon-github"></i><span class="hidden-phone">&nbsp;Github</span></a></li>
                        <li><a href="https://twitter.com/wuic_project" target="_blank"><i class="icon-twitter"></i><span class="hidden-phone">&nbsp;Twitter</span></a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    </div>
++++

== General architecture and terminology

WUIC is designed to integrate many architectures. This is possible thanks to the following abstract concepts:

* *Nut*: this is an abstraction of your static file providing its type (JS/CSS) and the stream allowing to read it
* *DAO*: the Data Access Object pattern is used to define the NutDao interface, allowing to manage nuts
* *Heap*: this is a set of nuts that you use to organize them
* *Engine*: the engine is a class which can process your nuts with a particular role (caching, aggregating, compressing, etc)
* *Workflow*: Associates a heap to a *chain of responsibility* composed of engines. This way, the workflow describes how you want to process your nuts.

The following diagram shows the architecture used by WUIC to optimize your website on the fly:

[ditaa, target="ditaa-diagram"]
----

 /----------------------------------------------------------------------------------------------\
 |                                     +------------------+                                     |
 |                                     | Servlet Container|                                     |
 |                                     +------------------+                                     |
 |                                                                                              |
 |                                                                                              |
 |    /------------------------------------------------\                              Requires  |   +---------+
 |    |                                                |  +-----------------------+ the page (1)|   |         |
 |    |                      Workflow invocation (2a)  |  |   WUIC Servlet Filter |<------------|---|         |
 |    |                   +----------------------------|--|        AND / OR       |-------------|-->|         |
 |    |                   |                            |  |     Tag processor     | Transformed |   |         |
 |    |                   |                            |  | (like Thymeleaf or JSP| result (7)  |   |         |
 |    |                   |                            |  +-----------------------+             |   |         |
 |    |                   v               Workflow     |                                        |   | Browser |
 |    |             +------------+    invocation (2b)  |  +--------------+   Requires fetched   |   |         |
 |    |             |Workflow "W"|<--------------------|--|              | page's resources (8) |   |         |
 |    |             +------------+                     |  | WUIC Servlet |<---------------------|---|         |
 |    |                   ^                            |  |              |----------------------|-->|         |
 |    |                   |                            |  +--------------+ Optimized result (9) |   +---------+
 |    |                   |                            |                                        |
 |    |                   |                            |                   /---------------\    |
 |    |     +--------------------+                     |                   |  +---------+  |    |
 |    |     | Processed Nuts are |                     |                   |  |Nuts Heap|  |    |
 |    |     |    returned (6)    |                     |                   |  +---------+  |    |
 |    |     +--------------------+          +-------------------------+    |               |    |
 |    |                   |                 | Treat the nuts from the |    |  +---------+  |    |
 |    |                   |---------------->|   associated heap (3)   |--->|  |  Nut 1  |  |    |
 |    |                   |                 +-------------------------+    |  +---------+  |    |
 |    |     +-----------------------------+            |                   |               |    |
 |    |     | Nuts processed by the chain |            |                   |  +---------+  |    |
 |    |     |    of responsibility (5)    |            |                   |  |  Nut 2  |  |    |
 |    |     +-----------------------------+            |                   |  +---------+  |    |
 |    |                   |                            |                   |               |    |
 |    |                   v                            |                   |  +---------+  |    |
 |    |           +---------------+                    |                   |  |  Nut N  |  |    |
 |    |           | Engine 1 (5a) |                    |                   |  +---------+  |    |
 |    |           +---------------+                    |                   \---------------/    |
 |    |                   |                            |                           |            |
 |    |           +---------------+                    |          Creates nut with |            |
 |    |           | Engine 2 (5b) |                    |         associated DAO (4)|            |
 |    |           +---------------+                    |                           v            |
 |    |                   |                            |                   /---------------\    |
 |    |             +-----------+                      |                   |  Nut DAO "D"  |    |
 |    |             | Engine... |                      |                   \---------------/    |
 |    |             +-----------+                      |                                        |
 |    |                   |                            |                                        |
 |    |           +---------------+                    |                                        |
 |    |           | Engine 3 (5n) |                    |                                        |
 |    |           +---------------+                    |                                        |
 |    |                                                |                                        |
 |    \------------------------------------------------/                                        |
 |                                                                                              |
 \----------------------------------------------------------------------------------------------/
----

*Step 1*
The browser requires the page corresponding to the link in the address bar on the server.
The server can directly serve a HTML page, which can be filtered by the WUIC servlet filter that optimizes it and all its referenced resources.
The HTML can also be produced by a processor like JSP or Thymeleaf (which could also be filtered by the WUIC servlet filter).
WUIC tags for those libraries can also be called during template processing to generate links pointing to optimized resources.

*Step 2*
A workflow is executed according to the information associated to the requested page.
For now, just remember that in WUIC, a workflow describes the way you want to process a set of statics.
The workflow could be created on the fly by the servlet filter or a workflow referenced manually inside a template (through JSP or Thymeleaf).

*Step 2a:* the invoked workflow corresponds at least to the resources referenced in the HTML page, and possibly to the HTML page itself if the servlet filter is installed.

*Step 3*
When a workflow needs to be executed, WUIC looks at first for the statics to be processed.
They are provided by an associated *heap*.
A heap is also identified by an ID and just contains a set of paths representing the statics to be loaded.

*Step 4*
The heap just has the paths representing the statics, but it can't open the stream to them itself.
It consequently uses an associated *DAO* which, thanks to a given path, can provide access to the stream.
Remember: the DAO will produce a *nut*.
Nut is the term that will be used everywhere in WUIC to represent your static (or you also called a resource).

*Step 5*
Once the nuts have been returned by the heap, then a *chain of responsibility* composed of *engines* is called to process the nuts.
Each engine has a particular purpose. There is an engine for caching, compressing, inspecting or aggregating nuts.

*Step 6*
Once nuts have been processed by engines, they are returned by the invoker (a servlet, a filter or a tag processor).

*Step 7*
The result is sent to the browser. If the result contains the optimized version of the required page, then its content is written to the HTTP response.
Otherwise, the result is sent under the form of a link added to the HTML page which points to the WUIC servlet.
Note that the resource can also be pushed to the client if HTTP/2 is enabled.

*Step 8*
When the page is fetched by the browser, additional resources (JS, CSS, etc) that have been processed by WUIC could be referenced as links.
The links are used to submit a new HTTP request to the WUIC servlet.

*Step 9*
The WUIC servlet extracts the requested name of the result entry for the specified workflow to be written to the HTTP response.

*Step 2b*: when a particular resource is requested, the WUIC servlet executes the workflow like in step 2 to retrieve the content to write.
However, you can be sure that the workflow will be executed pretty fast, as a result already exists in the internal cache.

== Dependency management

=== Reduce dependencies

WUIC tries to reduce as much as possible the dependencies of the project.
However, we know that we will still depend of some third party libraries because of the complexity of the feature and/or the well known API they provide.

Artifacts are organized in two major repositories:

* https://github.com/wuic/wuic/[core]: minimal configurations to get essential features in J2SE/JEE environment. It is very light and comes only with two dependencies in runtime scope.
* https://github.com/wuic/wuic-extensions[extensions]: additional features implemented on top of third-party libraries.

You can see in action design decisions explained bellow by taking a look at the `pom.xml` of the project and our https://github.com/wuic/wuic-samples[samples].

=== Core dependencies

==== SLF4J for logging

We decided to use the famous `SLF4J` API as logger facade in the WUIC project.
Every features are based on the `wuic-core` artifact which comes this dependency: `org.slf4j:sl4j-api`

As explained by the SL4FJ documentation, you will have to add in your project the concrete logging API and its corresponding `SLF4J` binder you want to use.

==== ASL Annotation Detector

ASL Annotation Detector is a very light project packaged in a single JAR.
It's used by `wuic-core` to detect automatically extensions added by the user by scanning the classpath.

IMPORTANT: this library's code is currently embedded in WUIC as it fixes a bug on JBoss/Wildfly not resolved in upstream.

==== Provided JEE dependencies

Finally, the core repository also provide JEE supports.
In addition to the `wuic-core` dependency, those artifacts declare additional dependencies in provided scope because they're already provided by the servlet container.

=== Extensions

Some protocols supports are included in the core (like HTTP) because they are not based on any external project.

For others like FTP or SSH, we needed to use some projects like `JSCH` or `commons-net` making the protocols easy to use.
Each protocol support which requires additional dependencies comes in a separate module you need to include.

The issue is the same for processors.
For instance, aggregation is provided by core but minification is enabled only when you add an extension which comes with third party library like `YUICompressor`.

If you want to use an extension which comes with specific dependencies, you'll have to put it in your pom.xml :

[source,xml]
----
    <dependency>
        <groupId>com.github.wuic.extension</groupId>
        <artifactId>${wuic-extension-name}</artifactId>
        <version>${wuic-extension.version}</version>
    </dependency>
----

== Configuration structure

=== Purpose

Organizing, processing and serving web assets is related to a lot of technical considerations and settings.
This document helps to understand how WUIC organizes its configuration points to address those several issues.

=== Key components

The central component used inside WUIC is the http://wuic.github.io/apidocs/com/github/wuic/Context.html[Context]. It knows:

* How statics are organized (nuts inside heaps)
* How statics are processed (workflows)

It's built thanks to a http://wuic.github.io/apidocs/com/github/wuic/ContextBuilder.html[ContextBuilder].
This builder could be configured with several http://wuic.github.io/apidocs/com/github/wuic/ContextBuilderConfigurator.html[ContextBuilderConfigurator].
The `wuic.xml` file is for instance read by a http://wuic.github.io/apidocs/com/github/wuic/ContextBuilderConfigurator.html[ContextBuilderConfigurator].

Building the context is automated and managed transparently by the http://wuic.github.io/apidocs/com/github/wuic/WuicFacade.html[WuicFacade].
Its state also contains additional information regarding how the process result is served to client.
The facade could be built with a http://wuic.github.io/apidocs/com/github/wuic/WuicFacadeBuilder.html[WuicFacadeBuilder].
The `web.xml` can declare several facade settings to let a http://wuic.github.io/apidocs/com/github/wuic/servlet/WuicServletContextListener.html[ContextListener] bootstrap WUIC.

=== Conclusion

You can delegate facade instantiation to a servlet listener in your web.xml and configure the underlying WUIC context with a `wuic.xml` file.
You can also complete or replace configuration with `Java Config`.
Take a look at the different API references to see details.

++++
<!-- javascript
=================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-40383819-1', 'github.io');
    ga('send', 'pageview');
</script>
++++