:toc: right
:toc-title: More 5 minutes tutorials

++++
    <!-- styles -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="wiki-css/theme.css" rel="stylesheet" />
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">
    <link rel="icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">

    <div class="masthead">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav" role="navigation">
                        <!-- Logo and slogan -->
                        <li><a href="index.html"><i class="icon-home"></i><span class="hidden-phone">&nbsp;Home</span></a></li>
                        <li><a href="project.html"><i class="icon-star"></i><span class="hidden-phone">&nbsp;Project</span></a></li>
                        <li class="active"><a href="documentation.html"><i class="icon-book"></i><span class="hidden-phone">&nbsp;Documentation</span></a></li>
                        <li><a href="contact.html"><i class="icon-envelope"></i><span class="hidden-phone">&nbsp;Contact</span></a></li>
                        <li><a href="https://github.com/wuic/wuic" target="_blank" title="Wuic Github"><i class="icon-github"></i><span class="hidden-phone">&nbsp;Github</span></a></li>
                        <li><a href="https://twitter.com/wuic_project" target="_blank"><i class="icon-twitter"></i><span class="hidden-phone">&nbsp;Twitter</span></a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    </div>
++++

== AngularJS

=== Feature

WUIC provides out of the box an `AngularJS` support and optimize the `templateUrl` option by default!
This topic gives you the details.

===  Writing your directives

AngularJS is MV* framework which advises the use of custom directives. As described in https://docs.angularjs.org/guide/directive[the documentation]:

[lead]
Best Practice: Unless your template is very small, it's typically better to break it apart into its own HTML file and load it with the `templateUrl` option.

This means that when `AngularJS` will instantiate the directive, an additional HTTP request will be executed to load the template content.
This leads to two issues:

* the user must waits the HTTP request is done to see the content displayed
* you should take care of client cache, which must be burst each time you deploy a new version with a different template

### Inlining

WUIC takes care of templateUrl occurrences in javascript code and replace it with a template option.

For example, imagine you have the following directory tree:

----
    .
    |--app
       |--myFeature
          |--directive
             `-- myDirective.js
          |--template
             `-- myTemplate.html
----

`myTemplate.html`:


[source,html]
----
    <h1>My Template  Title</h1>
----

In your `myDirective.js` file, you can refer myTemplate.html with an URL relative to your script location:


[source,javascript]
----
    myModule.directive('myDirective', function() {
       return {
           templateUrl: '../template/myTemplate.html'
       };
    });
----

When WUIC parses `myTemplate.js`, you will obtain something like that:

[source,javascript]
----
    myModule.directive('myDirective', function() {
       return {
           template: '<h1>My Template  Title</h1>'
       };
    });
----

WUIC solves two issues:

* You save the additional HTTP request
* As each file processed by WUIC is served with a different URL each time the content change, you make sure the client cache is burst when you update the template

=== Best effort

Note that in best effort mode, WUIC serves the content as fast as possible and just rewrite the template URL, without running inlining process.

=== Natural Templating

If you want to mix natural templating and WUIC's `AngularJS` optimization feature, you must read this important page (TODO: migrate https://github.com/wuic/wuic/wiki/Natural-Templating-with-AngularJS).

++++
<!-- javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-40383819-1', 'github.io');
    ga('send', 'pageview');
</script>
++++
