:toc: right

++++
    <!-- styles -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="wiki-css/theme.css" rel="stylesheet" />
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">
    <link rel="icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">

    <div class="masthead">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav" role="navigation">
                        <!-- Logo and slogan -->
                        <li><a href="index.html"><i class="icon-home"></i><span class="hidden-phone">&nbsp;Home</span></a></li>
                        <li><a href="project.html"><i class="icon-star"></i><span class="hidden-phone">&nbsp;Project</span></a></li>
                        <li class="active"><a href="documentation.html"><i class="icon-book"></i><span class="hidden-phone">&nbsp;Documentation</span></a></li>
                        <li><a href="contact.html"><i class="icon-envelope"></i><span class="hidden-phone">&nbsp;Contact</span></a></li>
                        <li><a href="https://github.com/wuic/wuic" target="_blank" title="Wuic Github"><i class="icon-github"></i><span class="hidden-phone">&nbsp;Github</span></a></li>
                        <li><a href="https://twitter.com/wuic_project" target="_blank"><i class="icon-twitter"></i><span class="hidden-phone">&nbsp;Twitter</span></a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    </div>
++++

== Supported server and known issues

WUIC is designed to be deployed in any `Servlet 3` compatible server running on top of `Java 6` and above:

* `Jetty` since `8.0`
* `Tomcat` since `7.0`
* `GlassFish` since `3.0`
* `JBoss` since `6.0`
* `WebLogic` since `12.0`
* `Undertow` since `1.0`

However, some features have a limited support on some specific version.
Known issues are identified with a link to the details and workaround in the table below.

++++
<table>
  <tr>
    <td><b>Feature/Servlet Container</b></td>
    <td>Jetty</td>
    <td>Tomcat</td>
    <td>GlassFish</td>
    <td>JBoss</td>
    <td>WebLogic</td>
    <td>Undertow (Wildfly)</td>
  </tr>
  <tr>
    <td><a href="#_unknown_mime_type_in_filter">Unknown MIME type in Filter</a></td>
    <td>OK</td>
    <td>OK</td>
    <td>Test needed!</td>
    <td>Test needed!</td>
    <td>Test needed!</td>
    <td>Before 1.1 (Wildfly 8.1)</td>
  </tr>
  <tr>
    <td><a href="#_best_effort_warmup_polling_and_async_version_computation">Best effort, warmup, polling and async version computation</a></td>
    <td>Since 9.3.0.M2</td>
    <td>OK</td>
    <td>Test needed!</td>
    <td>Test needed!</td>
    <td>Test needed!</td>
    <td>Before 1.2</td>
  </tr>
</table>
++++

=== Unknown MIME type in Filter

Because of https://issues.jboss.org/browse/UNDERTOW-268[UNDERTOW-268] issue, WUIC's servlet filter will fails if you deploy it on Undertow 1.0 (which is the default HTTP server in Wildfly 8.0 and 8.1).

A workaround exist: create a filter that force the mime type on resources filtered by WUIC. For instance:

[source,java]
----
include::{sample-repository}bootstrap3-sample/src/main/java/com/github/wuic/sample/MimeTypeFilter.java[tags=MimeTypeFilter]
----

=== Best effort, warmup, polling and async version computation

When a `Nut` is created with the `RequestDispatcherNutDao` component, the path is resolve with the `ServletContext#getResource(String)`
method, which works fine in any servlet container.

However, the content is dynamic (generated by a `Servlet` or a `JSP`), you must tell WUIC to use `RequestDispatcher#include(HttpServletRequest,HttpServletResponse)`
thanks to the `c.g.wuic.dao.useIncludeForPathPattern` that accepts a regex matching the desired path.
The problem is that following references explain that any attempt to use a `RequestDispatcher` outside the HTTP request/response lifecycle and/or in another thread will fail:

* https://issues.jboss.org/browse/UNDERTOW-357[UNDERTOW-357 fixed in 1.2]
* https://github.com/eclipse/jetty.project/commit/c23f21c761ff56f2ad4841a98083b237494442de#commitcomment-10495706[Optimization in Jetty 9.3 that won't be removed]

This lead to the following limitations when you use the `RequestDispatcherNutDao`, which is the default DAO in the `HtmlParserFilter`:

* Warmup strategy must be set to NONE (default setting)
* Version number must be computed synchronously (done asynchronously by default)
* Nut polling must be disabled (default setting)
* Cache engines must disable best effort (default setting)

Considering those points, you should be ok if you configure your `wuic.properties` like this when you use `RequestDispatcherNutDao`:

----
c.g.wuic.computeVersionAsynchronously=false
c.g.wuic.engine.bestEffort=false
----

++++
<!-- javascript
=================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-40383819-1', 'github.io');
    ga('send', 'pageview');
</script>
++++