:toc: right

++++
    <!-- styles -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="wiki-css/theme.css" rel="stylesheet" />
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">
    <link rel="icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">

    <div class="masthead">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav" role="navigation">
                        <!-- Logo and slogan -->
                        <li><a href="index.html"><i class="icon-home"></i><span class="hidden-phone">&nbsp;Home</span></a></li>
                        <li><a href="project.html"><i class="icon-star"></i><span class="hidden-phone">&nbsp;Project</span></a></li>
                        <li class="active"><a href="documentation.html"><i class="icon-book"></i><span class="hidden-phone">&nbsp;Documentation</span></a></li>
                        <li><a href="contact.html"><i class="icon-envelope"></i><span class="hidden-phone">&nbsp;Contact</span></a></li>
                        <li><a href="https://github.com/wuic/wuic" target="_blank" title="Wuic Github"><i class="icon-github"></i><span class="hidden-phone">&nbsp;Github</span></a></li>
                        <li><a href="https://twitter.com/wuic_project" target="_blank"><i class="icon-twitter"></i><span class="hidden-phone">&nbsp;Twitter</span></a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    </div>
++++

== Welcome to WUIC documentation page

This documentation gathers all information you need to use Web UI Compressor, the web assets optimizers for the JVM.
Before going deeper, you may take a look at the http://wuic.github.io[website index] for a general introduction ;-)

Find the documentation for following purpose:

* <<Optimize webapp performances>>
* <<How to extend WUIC>>
* <<How to use WUIC in my framework>>

== Optimize webapp performances

=== Step-by-step 5 minutes tutorials

If you want to see WUIC directly in action and play with it, you can directly jump into our link:tutorials.html[step-by-step 5 minutes tutorials].
You can also see several samples https://github.com/wuic/wuic-samples[here].

=== Going deeper

If you want to go deeper, you can read our set of articles describing all the implemented concepts.
You can start by reading the <<General architecture and terminology>> section.

Then, follow the step-by-step tutorials that illustrate how you can start very quickly with automatic optimizations and
then gradually enable more WUIC features to capitalize on all offered possibilities:

* Configure WUIC to serve your statics from your servlet container and install the servlet filter that optimize your HTML page
* Enable automatically extensions just by adding dependencies
* Generate your scripts imports statements in your HTML page thanks to JSP or Thymeleaf support
* Manage your statics with XML configuration file
* Process your raw statics at runtime

=== API

After this, you'll find in the side bar the detailed documentation regarding each followed steps in the tutorials:

* Complete XML configuration documentation (TODO: migrate https://github.com/wuic/wuic/wiki/Understanding-wuic.xml)
* Complete web.xml configuration (TODO: migrate https://github.com/wuic/wuic/wiki/Configuring-web.xml)
* Available engines (TODO: migrate https://github.com/wuic/wuic/wiki/Engine-configuration) and [DAO](https://github.com/wuic/wuic/wiki/Data-Access-Object)

== How to extend WUIC

WUIC is designed to be extended easily. You will find a complete advanced tutorial [here](https://github.com/wuic/wuic/wiki/Create-an-extension).

== How to use WUIC in my framework

If you want to build a part of your framework on top of WUIC, you don't have to ask your users to use XML configuration file.
You can totally hide this configuration point by using Java Config (TODO: migrate https://github.com/wuic/wuic/wiki/Configuring-with-Java-Config).

Then you will find implementation details directly in the javadoc (TODO: migrate http://wuic.github.io/apidocs/index.html).

== General architecture and terminology

WUIC is designed to integrate many architectures. This is possible thanks to the following abstract concepts:

* *Nut*: this is an abstraction of your static file providing its type (JS/CSS) and the stream allowing to read it
* *DAO*: the Data Access Object pattern is used to define the NutDao interface, allowing to manage nuts
* *Heap*: this is a set of nuts that you use to organize them
* *Engine*: the engine is a class which can process your nuts with a particular role (caching, aggregating, compressing, etc)
* *Workflow*: Associates a heap to a *chain of responsibility* composed of engines. This way, the workflow describes how you want to process your nuts.

The following diagram shows the architecture used by WUIC to optimize your website on the fly:

[ditaa, target="ditaa-diagram"]
----

 /----------------------------------------------------------------------------------------------\
 |                                     +------------------+                                     |
 |                                     | Servlet Container|                                     |
 |                                     +------------------+                                     |
 |                                                                                              |
 |                                                                                              |
 |    /------------------------------------------------\                              Requires  |   +---------+
 |    |                                                |  +-----------------------+ the page (1)|   |         |
 |    |                      Workflow invocation (2a)  |  |   WUIC Servlet Filter |<------------|---|         |
 |    |                   +----------------------------|--|        AND / OR       |-------------|-->|         |
 |    |                   |                            |  |     Tag processor     | Transformed |   |         |
 |    |                   |                            |  | (like Thymeleaf or JSP| result (7)  |   |         |
 |    |                   |                            |  +-----------------------+             |   |         |
 |    |                   v               Workflow     |                                        |   | Browser |
 |    |             +------------+    invocation (2b)  |  +--------------+   Requires fetched   |   |         |
 |    |             |Workflow "W"|<--------------------|--|              | page's resources (8) |   |         |
 |    |             +------------+                     |  | WUIC Servlet |<---------------------|---|         |
 |    |                   ^                            |  |              |----------------------|-->|         |
 |    |                   |                            |  +--------------+ Optimized result (9) |   +---------+
 |    |                   |                            |                                        |
 |    |                   |                            |                   /---------------\    |
 |    |     +--------------------+                     |                   |  +---------+  |    |
 |    |     | Processed Nuts are |                     |                   |  |Nuts Heap|  |    |
 |    |     |    returned (6)    |                     |                   |  +---------+  |    |
 |    |     +--------------------+          +-------------------------+    |               |    |
 |    |                   |                 | Treat the nuts from the |    |  +---------+  |    |
 |    |                   |---------------->|   associated heap (3)   |--->|  |  Nut 1  |  |    |
 |    |                   |                 +-------------------------+    |  +---------+  |    |
 |    |     +-----------------------------+            |                   |               |    |
 |    |     | Nuts processed by the chain |            |                   |  +---------+  |    |
 |    |     |    of responsibility (5)    |            |                   |  |  Nut 2  |  |    |
 |    |     +-----------------------------+            |                   |  +---------+  |    |
 |    |                   |                            |                   |               |    |
 |    |                   v                            |                   |  +---------+  |    |
 |    |           +---------------+                    |                   |  |  Nut N  |  |    |
 |    |           | Engine 1 (5a) |                    |                   |  +---------+  |    |
 |    |           +---------------+                    |                   \---------------/    |
 |    |                   |                            |                           |            |
 |    |           +---------------+                    |          Creates nut with |            |
 |    |           | Engine 2 (5b) |                    |         associated DAO (4)|            |
 |    |           +---------------+                    |                           v            |
 |    |                   |                            |                   /---------------\    |
 |    |             +-----------+                      |                   |  Nut DAO "D"  |    |
 |    |             | Engine... |                      |                   \---------------/    |
 |    |             +-----------+                      |                                        |
 |    |                   |                            |                                        |
 |    |           +---------------+                    |                                        |
 |    |           | Engine 3 (5n) |                    |                                        |
 |    |           +---------------+                    |                                        |
 |    |                                                |                                        |
 |    \------------------------------------------------/                                        |
 |                                                                                              |
 \----------------------------------------------------------------------------------------------/
----

*Step 1*
The browser requires the page corresponding to the link in the address bar on the server.
The server can directly serve a HTML page, which can be filtered by the WUIC servlet filter that optimizes it and all its referenced resources.
The HTML can also be produced by a processor like JSP or Thymeleaf (which could also be filtered by the WUIC servlet filter).
WUIC tags for those libraries can also be called during template processing to generate links pointing to optimized resources.

*Step 2*
A workflow is executed according to the information associated to the requested page.
For now, just remember that in WUIC, a workflow describes the way you want to process a set of statics.
The workflow could be created on the fly by the servlet filter or a workflow referenced manually inside a template (through JSP or Thymeleaf).

*Step 2a:* the invoked workflow corresponds at least to the resources referenced in the HTML page, and possibly to the HTML page itself if the servlet filter is installed.

*Step 3*
When a workflow needs to be executed, WUIC looks at first for the statics to be processed.
They are provided by an associated *heap*.
A heap is also identified by an ID and just contains a set of paths representing the statics to be loaded.

*Step 4*
The heap just has the paths representing the statics, but it can't open the stream to them itself.
It consequently uses an associated *DAO* which, thanks to a given path, can provide access to the stream.
Remember: the DAO will produce a *nut*.
Nut is the term that will be used everywhere in WUIC to represent your static (or you also called a resource).

*Step 5*
Once the nuts have been returned by the heap, then a *chain of responsibility* composed of *engines* is called to process the nuts.
Each engine has a particular purpose. There is an engine for caching, compressing, inspecting or aggregating nuts.

*Step 6*
Once nuts have been processed by engines, they are returned by the invoker (a servlet, a filter or a tag processor).

*Step 7*
The result is sent to the browser. If the result contains the optimized version of the required page, then its content is written to the HTTP response.
Otherwise, the result is sent under the form of a link added to the HTML page which points to the WUIC servlet.
Note that the resource can also be pushed to the client if HTTP/2 is enabled.

*Step 8*
When the page is fetched by the browser, additional resources (JS, CSS, etc) that have been processed by WUIC could be referenced as links.
The links are used to submit a new HTTP request to the WUIC servlet.

*Step 9*
The WUIC servlet extracts the requested name of the result entry for the specified workflow to be written to the HTTP response.

*Step 2b*: when a particular resource is requested, the WUIC servlet executes the workflow like in step 2 to retrieve the content to write.
However, you can be sure that the workflow will be executed pretty fast, as a result already exists in the internal cache.

++++
<!-- javascript
=================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-40383819-1', 'github.io');
    ga('send', 'pageview');
</script>
++++