:toc: right

++++
    <!-- styles -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="wiki-css/theme.css" rel="stylesheet" />
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet" />
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Favicon -->
    <link rel="shortcut icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">
    <link rel="icon" href="wiki-images/logo/favicon.ico" type="image/x-icon">

    <div class="masthead">
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav" role="navigation">
                        <!-- Logo and slogan -->
                        <li><a href="index.html"><i class="icon-home"></i><span class="hidden-phone">&nbsp;Home</span></a></li>
                        <li><a href="project.html"><i class="icon-star"></i><span class="hidden-phone">&nbsp;Project</span></a></li>
                        <li class="active"><a href="documentation.html"><i class="icon-book"></i><span class="hidden-phone">&nbsp;Documentation</span></a></li>
                        <li><a href="contact.html"><i class="icon-envelope"></i><span class="hidden-phone">&nbsp;Contact</span></a></li>
                        <li><a href="https://github.com/wuic/wuic" target="_blank" title="Wuic Github"><i class="icon-github"></i><span class="hidden-phone">&nbsp;Github</span></a></li>
                        <li><a href="https://twitter.com/wuic_project" target="_blank"><i class="icon-twitter"></i><span class="hidden-phone">&nbsp;Twitter</span></a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    </div>
++++

== Welcome to WUIC documentation page

This documentation gathers all information you need to use Web UI Compressor, the web assets optimizers for the JVM.
Before going deeper, you may take a look at the http://wuic.github.io[website index] for a general introduction ;-)

Find the documentation for following purpose:

* <<Optimize webapp performances>>
* <<How to extend WUIC>>
* <<How to use WUIC in my framework>>

=== FAQ

Please find our FAQ section link:faq.html[here].

== Optimize webapp performances

=== Step-by-step 5 minutes tutorials

If you want to see WUIC directly in action and play with it, you can directly jump into our link:tutorials.html[step-by-step 5 minutes tutorials].
You can also see several samples https://github.com/wuic/wuic-samples[here].

=== Going deeper

If you want to go deeper, you can read our set of articles describing all the implemented concepts.
You can start by the link:design.html[design] page and reading at least the `General architecture and terminology` section.

Then, follow the step-by-step tutorials that illustrate how you can start very quickly with automatic optimizations and
then gradually enable more WUIC features to capitalize on all offered possibilities:

* Configure WUIC to serve your statics from your servlet container and install the servlet filter that optimize your HTML page
* Enable automatically extensions just by adding dependencies
* Generate your scripts imports statements in your HTML page thanks to JSP or Thymeleaf support
* Manage your statics with XML configuration file
* Process your raw statics at runtime

=== More tutorials

WUIC provides extension to support several frameworks and languages like `Spring`, `AngularJS` or `Typescript`.
You will find more tutorials about that link:more-tutorials.html[here].

=== API

After this, you'll find below the detailed documentation about different components browsed in the tutorials:

* <<api.html#_configuring_the_wuic_xml,Complete wuic.xml configuration>>
* <<api.html#_configuring_the_web_xml,Complete web.xml configuration>>
* <<api.html#_built_in_html_templating,Built-in HTML templating>>
* <<api.html#_java_config,Java Config alternative>>
* Available engines (TODO: migrate https://github.com/wuic/wuic/wiki/Engine-configuration) and [DAO](https://github.com/wuic/wuic/wiki/Data-Access-Object)

== How to extend WUIC

WUIC is designed to be extended easily. You will find a complete advanced tutorial [here](https://github.com/wuic/wuic/wiki/Create-an-extension).

== How to use WUIC in my framework

If you want to build a part of your framework on top of WUIC, you don't have to ask your users to use XML configuration file.
You can totally hide this configuration point by using <<api.html#_java_config,Java Config>>.

Then you will find implementation details directly in the http://wuic.github.io/apidocs/index.html[javadoc].

++++
<!-- javascript
=================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
<script src="bootstrap/js/bootstrap.js"></script>
<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-40383819-1', 'github.io');
    ga('send', 'pageview');
</script>
++++